window.DirectCreditData = (() => {
  const base = (window.DIRECTCREDIT_API_URL || localStorage.getItem('directcredit_api_url') || '/api').replace(/\/$/, '');
  const headers = () => { const token=localStorage.getItem('directcredit_admin_token') || window.DIRECTCREDIT_ADMIN_TOKEN; return token ? {Accept:'application/json',Authorization:`Bearer ${token}`} : {Accept:'application/json'}; };
  async function get(path){const r=await fetch(`${base}${path}`,{headers:headers()});if(!r.ok)throw new Error(`API ${r.status}`);return r.json()}
  async function reporting(){return get('/admin/reporting')}
  async function loans(){return get('/admin/loans')}
  const parsed=v=>{if(v==null)return v;if(typeof v!=='string')return v;try{return JSON.parse(v)}catch(_){return v}};
  async function customer(id){const [cr,lr]=await Promise.all([get(`/customers/${encodeURIComponent(id)}`),loans()]);const rows=lr.filter(x=>Number(x.customer_id)===Number(id));const outstanding=rows.reduce((s,x)=>s+Number(x.outstanding_amount||0),0);const paid=rows.reduce((s,x)=>s+Math.max(Number(x.disbursed_amount||0)-Number(x.outstanding_amount||0),0),0);const overdue=rows.filter(x=>x.status==='overdue').reduce((s,x)=>s+Number(x.outstanding_amount||0),0);const latest=rows[0]||{};return {customer:cr,loans:rows,metrics:{total_loans:rows.length,total_loan_amount:rows.reduce((s,x)=>s+Number(x.sanctioned_amount||x.requested_amount||0),0),outstanding_amount:outstanding,amount_paid:paid,overdue_amount:overdue},bank_analysis:{status:cr.primary_bank?'Customer banking field recorded':'No bank account data connected'},kyc_employment:{kyc_status:cr.kyc_status,employment_type:cr.occupation,income:cr.monthly_income,work_experience_years:cr.work_experience_years,years_in_business:cr.years_in_business,residence_ownership:cr.residence_ownership,ownership_proof_status:cr.ownership_proof_status},risk_score:{total_score:latest.scorecard_score??null,max_score:latest.scorecard_max??125,risk_tier:latest.scorecard_decision==='REJECT'?'High Risk':latest.scorecard_score>=105?'Low Risk':latest.scorecard_score>=95?'Moderate Risk':'Not assessed',decision:latest.scorecard_decision||'Not assessed',credit_score:cr.cibil_score||null,source:latest.scorecard_score!=null?'scorecard':'scorecard_not_configured',scorecard_version:latest.scorecard_version||'MBL-125-v1',approval_percent:latest.scorecard_approval_percent??null,reasons:parsed(latest.scorecard_reasons)||[],hard_rejects:parsed(latest.scorecard_hard_rejects)||[],factor_scores:parsed(latest.scorecard_factor_scores)||{}}};}
  return {base,headers,reporting,customer,loans};
})();
