const pages=[...document.querySelectorAll('.page')];
const navs=[...document.querySelectorAll('.nav')];
const titles={application:'Loan Application',dashboard:'Dashboard',bank:'Bank Statement Analysis',risk:'Risk & Score Breakdown',repayment:'Repayment Matrix'};
const steps=[
  {key:'pan',label:'PAN',title:'PAN Number',html:`<p>Enter PAN number. For now, verification uses temporary success confirmation.</p><label>PAN Number<input id="pan" placeholder="ABCDE1234F" maxlength="10"></label><button class="btn primary large" onclick="completeStep()">Verify PAN & Name</button>`},
  {key:'aadhaar',label:'Aadhaar OCR/Verification',title:'Aadhaar OCR / Verification',html:`<p>Upload Aadhaar card. OCR will capture Aadhaar data and profile details. Verification is temporary success in Demo Mode.</p><label>Aadhaar Card<input id="aadhaarFile" type="file" accept="image/*,.pdf"></label><button class="btn primary large" onclick="completeStep()">Upload, OCR & Verify Aadhaar</button>`},
  {key:'selfie',label:'Selfie',title:'Selfie',html:`<p>Capture or upload customer selfie.</p><label>Selfie<input id="selfieFile" type="file" accept="image/*" capture="user"></label><button class="btn primary large" onclick="completeStep()">Verify Selfie</button>`},
  {key:'bureau',label:'Bureau',title:'Bureau',html:`<p>Run bureau check. Demo Mode returns a temporary successful bureau result.</p><button class="btn primary large" onclick="completeStep()">Run Bureau Check</button>`},
  {key:'profile',label:'Profile',title:'Profile Details',html:`<p>Profile details are captured from Aadhaar. Customer can review and complete missing details.</p><div class="fields"><label>Name<input value="Captured from Aadhaar"></label><label>Date of Birth<input value="Captured from Aadhaar"></label><label>Address<input value="Captured from Aadhaar"></label><label>Mobile Number<input placeholder="Mobile Number"></label><label>Email<input placeholder="Email"></label><label>Business Name<input placeholder="Business Name"></label></div><button class="btn primary large" onclick="completeStep()">Confirm Profile Details</button>`},
  {key:'bank',label:'Bank Statement Upload & Our Analysis',title:'Bank Statement Upload & Our Analysis',html:`<p>Upload bank statement. DirectCredit performs bank analysis using our own techniques; no bank-analysis API is required.</p><label>Bank Statement<input id="bankFile" type="file" accept=".pdf,.csv,.xls,.xlsx"></label><button class="btn primary large" onclick="completeStep()">Upload & Analyse Bank Statement</button>`},
  {key:'documents',label:'Other Documents',title:'Other Documents',html:`<p>Upload applicable supporting documents.</p><div class="fields"><label>ITR<input type="file" accept=".pdf,image/*"></label><label>GST<input type="file" accept=".pdf,image/*"></label><label>Business Bills<input type="file" accept=".pdf,image/*"></label><label>Ownership Proof<input type="file" accept=".pdf,image/*"></label><label>Other Bank Account<input type="file" accept=".pdf,.csv,.xls,.xlsx"></label></div><button class="btn primary large" onclick="completeStep()">Save Other Documents</button>`},
  {key:'assessment',label:'Loan Assessment',title:'Loan Assessment',html:`<p>Assessment combines PAN, Aadhaar, Selfie, Bureau, Profile, Bank Statement Analysis and Other Documents.</p><div class="cards"><div class="card"><small>Assessment</small><strong>Eligible</strong></div><div class="card"><small>Risk</small><strong>Low Risk</strong></div><div class="card"><small>Score</small><strong>92.65 / 110</strong></div></div><button class="btn primary large" onclick="completeStep()">Complete Loan Assessment</button>`},
  {key:'sanction',label:'Sanction',title:'Approved Loan Amount — Sanction',html:`<div class="approval"><div><span class="badge green">APPROVED</span><h2>Micro Business Loan</h2><p>Approved Loan Amount</p><strong>₹15,000</strong></div><div><p>Repayment: <b>Monthly</b></p><p>Loan Range: <b>₹5,000–₹15,000</b></p></div></div><button class="btn primary large" onclick="completeStep()">Generate Sanction</button>`},
  {key:'customerApproval',label:'Customer Approval',title:'Customer Approval',html:`<p>Customer reviews the sanction and approves the loan offer.</p><div class="approval"><div><h2>Approved Loan Amount</h2><strong>₹15,000</strong></div><div><p>Repayment: <b>Monthly</b></p></div></div><button class="btn primary large" onclick="completeStep()">Customer Approves Loan</button>`},
  {key:'esign',label:'E-Sign',title:'E-Sign',html:`<p>E-Sign is currently configured as temporary Demo Success. Production will use the real E-Sign API.</p><button class="btn primary large" onclick="completeStep()">Complete E-Sign</button>`},
  {key:'disbursement',label:'Disbursement',title:'Disbursement',html:`<p>Disbursement is currently configured as temporary Demo Success. Production will use the real disbursement integration.</p><button class="btn primary large" onclick="completeStep()">Disburse Loan</button>`},
  {key:'repayment',label:'Repayment',title:'Repayment',html:`<p>Loan is disbursed. Monthly repayment schedule is now active.</p><table><thead><tr><th>Repayment</th><th>Due Date</th><th>Status</th></tr></thead><tbody><tr><td>Monthly Repayment 1</td><td>Next due date</td><td>Upcoming</td></tr><tr><td>Monthly Repayment 2</td><td>Following month</td><td>Upcoming</td></tr></tbody></table><button class="btn primary large" onclick="completeStep()">Mark Demo Repayment Success</button>`}
];
let current=Number(localStorage.getItem('dcCurrent')||0);
let completed=JSON.parse(localStorage.getItem('dcCompleted')||'[]');
function showPage(id){pages.forEach(p=>p.classList.toggle('activePage',p.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.page===id));document.getElementById('pageTitle').textContent=titles[id]||id;history.replaceState(null,'','#'+id);window.scrollTo({top:0,behavior:'smooth'});if(id==='dashboard')renderFunnel();}
navs.forEach(n=>n.addEventListener('click',()=>showPage(n.dataset.page)));
function renderJourney(){document.getElementById('journey').innerHTML=steps.map((s,i)=>`<button class="journeyStep ${completed.includes(s.key)?'done':''} ${i===current?'current':''}" onclick="goStep(${i})"><span>${i+1}</span>${s.label}</button>`).join('');}
function renderWizard(){const s=steps[current];document.getElementById('wizard').innerHTML=`<div class="panel wizardPanel"><div class="sectionHead"><div><span class="eyebrow">STEP ${current+1} OF ${steps.length}</span><h2>${s.title}</h2></div><span class="badge">Demo Mode</span></div>${s.html}<div id="successBox"></div></div>`;}
function goStep(i){if(i<=current||completed.includes(steps[i-1]?.key)){current=i;save();renderJourney();renderWizard();}}
function completeStep(){const s=steps[current];if(s.key==='pan'){const v=(document.getElementById('pan')?.value||'').trim().toUpperCase();if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(v)){alert('Enter a valid PAN format, for example ABCDE1234F.');return;}}
if(!completed.includes(s.key))completed.push(s.key);save();const box=document.getElementById('successBox');if(box)box.innerHTML=`<div class="success">✓ ${s.label} — Demo Success</div>`;setTimeout(()=>{if(current<steps.length-1){current++;save();renderJourney();renderWizard();}else{alert('Demo loan journey completed successfully.');showPage('repayment');}},550);}
function save(){localStorage.setItem('dcCurrent',String(current));localStorage.setItem('dcCompleted',JSON.stringify(completed));}
function resetJourney(){if(confirm('Reset the demo loan journey?')){current=0;completed=[];localStorage.removeItem('dcCurrent');localStorage.removeItem('dcCompleted');showPage('application');renderJourney();renderWizard();}}
function renderFunnel(){const el=document.getElementById('funnelRows');if(el)el.innerHTML=steps.map(s=>`<tr><td>${s.label}</td><td><span class="status ${completed.includes(s.key)?'ok':'warn'}">${completed.includes(s.key)?'Completed':'Pending'}</span></td></tr>`).join('');}
const initial=location.hash.slice(1);showPage(titles[initial]?initial:'application');renderJourney();renderWizard();