const API_BASE=(window.DIRECTCREDIT_API_URL||localStorage.getItem('directcredit_api_url')||'/api').replace(/\/$/,'');
const idFromUrl=()=>{const raw=new URLSearchParams(location.search).get('customer_id');return raw&&/^\d+$/.test(raw)?Number(raw):null};
const money=v=>v===null||v===undefined||v===''?'Not available':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v));
const text=(v,f='Not available')=>v===null||v===undefined||String(v).trim()===''?f:String(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(data){
 const c=data.customer||{},m=data.metrics||{},loans=data.loans||[],reps=data.repayments||[],docs=data.documents||[];
 document.getElementById('customerName').textContent=text(c.name,'Customer');
 document.getElementById('customerCode').textContent=text(c.customer_code||c.id);
 document.getElementById('avatar').textContent=String(c.name||'Customer').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'CU';
 const contact=[['Mobile Number',c.mobile],['Email Address',c.email],['Address',c.address],['Permanent Address',c.permanent_address],['Current City',c.current_city],['Business Name',c.business_name],['Business Type',c.business_type],['Date of Birth',c.date_of_birth],['PAN Number',c.pan],['Aadhaar Number',c.aadhaar_masked],['Marital Status',c.marital_status]];
 document.getElementById('contactList').innerHTML=contact.map(([k,v])=>`<div><label>${esc(k)}</label><b>${esc(text(v))}</b></div>`).join('');
 const metricValues=[text(m.total_loans,'0'),money(m.total_loan_amount),money(m.outstanding_amount),money(m.amount_paid),c.cibil_score?esc(c.cibil_score):'Not available'];
 [...document.querySelectorAll('#metrics .metric strong')].forEach((e,i)=>e.textContent=metricValues[i]);
 const summary=[['Customer Type',c.customer_type],['Occupation',c.occupation],['Monthly Income',c.monthly_income==null?null:money(c.monthly_income)],['Work Experience',c.work_experience_years==null?null:`${c.work_experience_years} years`],['Years in Business',c.years_in_business==null?null:`${c.years_in_business} years`],['Average Bank Balance',c.average_bank_balance==null?null:money(c.average_bank_balance)],['Primary Bank',c.primary_bank],['CIBIL Score',c.cibil_score],['FOIR',c.foir==null?null:`${c.foir}%`],['Existing EMI',c.existing_emi==null?null:money(c.existing_emi)],['KYC Status',c.kyc_status]];
 document.getElementById('summary').innerHTML=summary.map(([k,v])=>`<label>${esc(k)} <b>${esc(text(v))}</b></label>`).join('');
 const latest=loans[0];
 document.getElementById('latestLoan').innerHTML=latest?[['Loan Account',latest.id],['Product',latest.product],['Requested',money(latest.requested_amount)],['Eligible',money(latest.eligible_amount)],['Sanctioned',money(latest.sanctioned_amount)],['Disbursed',money(latest.disbursed_amount)],['EMI',money(latest.monthly_emi)],['Outstanding',money(latest.outstanding_amount)],['Tenure',latest.tenure_months?`${latest.tenure_months} months`:null],['Status',latest.status],['Current Stage',latest.current_stage]].map(([k,v])=>`<label>${esc(k)} <b>${esc(text(v))}</b></label>`).join(''):'<div class="empty-state">No live loan record exists for this customer.</div>';
 document.getElementById('loanRows').innerHTML=loans.length?loans.map(l=>`<tr><td>${esc(text(l.id))}</td><td>${esc(text(l.product))}</td><td>${esc(money(l.sanctioned_amount))}</td><td>${esc(money(l.outstanding_amount))}</td><td>${esc(money(l.monthly_emi))}</td><td>${esc(text(l.status))}</td></tr>`).join(''):'<tr><td colspan="6">No live loan records.</td></tr>';
 document.getElementById('repaymentRows').innerHTML=reps.length?reps.slice(0,10).map(r=>`<tr><td>${esc(text(r.due_date))}</td><td>${esc(text(r.loan_id))}</td><td>${esc(money(r.paid_amount||r.due_amount))}</td><td>${esc(text(r.status))}</td></tr>`).join(''):'<tr><td colspan="4">No live repayment records.</td></tr>';
 document.getElementById('documentRows').innerHTML=docs.length?docs.map(d=>`<tr><td>${esc(text(d.document_type))}</td><td>${esc(text(d.verification_status))}</td><td>${esc(d.created_at?new Date(d.created_at).toLocaleDateString('en-IN'):'Not available')}</td></tr>`).join(''):'<tr><td colspan="3">No live document records.</td></tr>';
}
async function load(){const id=idFromUrl();if(!id){document.querySelector('.right-area').innerHTML='<div class="panel empty-state"><h2>No customer selected</h2><p>Open this page with a valid customer_id from a live customer record.</p></div>';return;}try{const r=await fetch(`${API_BASE}/customers/${id}/profile`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(String(r.status));render(await r.json());}catch(e){document.querySelector('.right-area').innerHTML='<div class="panel empty-state"><h2>Live customer data unavailable</h2><p>No demo or fallback customer data is displayed.</p></div>';}}
load();
