const API_BASE=(window.DIRECTCREDIT_API_URL||localStorage.getItem('directcredit_api_url')||'/api').replace(/\/$/,'');
const adminHeaders=()=>{const t=localStorage.getItem('directcredit_admin_token')||window.DIRECTCREDIT_ADMIN_TOKEN;return t?{Accept:'application/json',Authorization:`Bearer ${t}`}:{Accept:'application/json'}};
const idFromUrl=()=>{const raw=new URLSearchParams(location.search).get('customer_id');return raw&&/^\d+$/.test(raw)?Number(raw):null};
const money=v=>v===null||v===undefined||v===''?'Not available':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v));
const text=(v,f='Not available')=>v===null||v===undefined||String(v).trim()===''?f:String(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(data){
 const c=data.customer||{},m=data.metrics||{},loans=data.loans||[],reps=data.repayments||[],docs=data.documents||[],risk=data.risk_score||{};
 document.getElementById('customerName').textContent=text(c.name,'Customer');document.getElementById('customerCode').textContent=text(c.customer_code||c.id);document.getElementById('avatar').textContent=String(c.name||'Customer').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'CU';
 const contact=[['Mobile Number',c.mobile],['Email Address',c.email],['Address',c.address],['Permanent Address',c.permanent_address],['Current City',c.current_city],['Business Name',c.business_name],['Business Type',c.business_type],['Date of Birth',c.date_of_birth],['PAN Number',c.pan],['Aadhaar Number',c.aadhaar_masked],['Marital Status',c.marital_status],['Residence Ownership',c.residence_ownership],['Residence Since',c.residence_since],['KYC Status',c.kyc_status],['Email Verification',c.email_verified?'Verified':'Pending']];document.getElementById('contactList').innerHTML=contact.map(([k,v])=>`<div><label>${esc(k)}</label><b>${esc(text(v))}</b></div>`).join('');
 const metricValues=[text(m.total_loans,'0'),money(m.total_loan_amount),money(m.outstanding_amount),money(m.amount_paid),c.cibil_score?esc(c.cibil_score):'Not available'];[...document.querySelectorAll('#metrics .metric strong')].forEach((e,i)=>e.textContent=metricValues[i]);
 const summary=[['Customer Type',c.customer_type],['Occupation',c.occupation],['Monthly Income',c.monthly_income==null?null:money(c.monthly_income)],['Work Experience',c.work_experience_years==null?null:`${c.work_experience_years} years`],['Years in Business',c.years_in_business==null?null:`${c.years_in_business} years`],['Average Bank Balance',c.average_bank_balance==null?null:money(c.average_bank_balance)],['Primary Bank',c.primary_bank],['CIBIL Score',c.cibil_score],['DirectCredit Score',risk.total_score==null?null:`${risk.total_score}/${risk.max_score||125}`],['Risk Tier',risk.risk_tier],['Decision',risk.decision],['Approval',risk.approval_percent==null?null:risk.approval_percent+'%'],['FOIR',c.foir==null?null:`${c.foir}%`],['Existing EMI',c.existing_emi==null?null:money(c.existing_emi)],['Dependents',c.dependents],['KYC Status',c.kyc_status]];document.getElementById('summary').innerHTML=summary.map(([k,v])=>`<label>${esc(k)} <b>${esc(text(v))}</b></label>`).join('');
 const detail=(id,rows)=>{const el=document.getElementById(id);if(el)el.innerHTML=rows.map(function(x){return '<div class="detail-item"><small>'+esc(x[0])+'</small><strong>'+esc(text(x[1]))+'</strong></div>'}).join('')};
 detail('identityDetails',[['Customer Code',c.customer_code||c.id],['Customer Type',c.customer_type],['Mobile',c.mobile],['Email',c.email],['PAN',c.pan],['Aadhaar',c.aadhaar_masked],['Date of Birth',c.date_of_birth],['Gender',c.gender],['Marital Status',c.marital_status],['City',c.current_city],['Residence',c.residence_ownership],['Residence Since',c.residence_since]]);
 detail('kycDetails',[['KYC Status',c.kyc_status],['Email Verified',c.email_verified?'Verified':'Pending'],['Selfie Status',c.selfie_status],['Occupation',c.occupation],['Business Name',c.business_name],['Business Type',c.business_type],['Monthly Income',c.monthly_income==null?null:money(c.monthly_income)],['Years in Business',c.years_in_business==null?null:c.years_in_business+' years'],['Work Experience',c.work_experience_years==null?null:c.work_experience_years+' years'],['Ownership Proof',c.ownership_proof_status],['Dependents',c.dependents],['Existing EMI',c.existing_emi==null?null:money(c.existing_emi)]]);
 detail('bankDetails',[['Primary Bank',c.primary_bank],['Average Bank Balance',c.average_bank_balance==null?null:money(c.average_bank_balance)],['Average Monthly Credit',money(data.bank_analysis&&data.bank_analysis.average_monthly_credit)],['Average Monthly Debit',money(data.bank_analysis&&data.bank_analysis.average_monthly_debit)],['Transactions',data.bank_analysis&&data.bank_analysis.total_transactions],['Negative Balance Events',data.bank_analysis&&data.bank_analysis.negative_balance_count],['Net Cash Flow',money((data.bank_analysis&&data.bank_analysis.average_monthly_credit||0)-(data.bank_analysis&&data.bank_analysis.average_monthly_debit||0))],['Outstanding',money(m.outstanding_amount)],['Overdue',money(m.overdue_amount)]]);
 detail('riskDetails',[['DirectCredit Score',risk.total_score==null?null:risk.total_score+'/'+(risk.max_score||125)],['Scorecard Version',risk.scorecard_version],['Risk Tier',risk.risk_tier],['Decision',risk.decision],['Approval',risk.approval_percent==null?null:risk.approval_percent+'%'],['CIBIL Score',c.cibil_score],['FOIR',c.foir==null?null:c.foir+'%'],['Existing EMI',c.existing_emi==null?null:money(c.existing_emi)],['Hard Rejects',(risk.hard_rejects||[]).length],['Reason Codes',(risk.reasons||[]).length],['Risk Source',risk.source]]);
 const latest=loans[0];
 detail('offerDetails',[['Latest Loan ID',latest&&latest.id],['Requested Amount',latest&&latest.requested_amount==null?null:latest&&money(latest.requested_amount)],['Eligible Amount',latest&&latest.eligible_amount==null?null:latest&&money(latest.eligible_amount)],['Sanctioned Amount',latest&&latest.sanctioned_amount==null?null:latest&&money(latest.sanctioned_amount)],['Disbursed Amount',latest&&latest.disbursed_amount==null?null:latest&&money(latest.disbursed_amount)],['Interest Rate',latest&&latest.interest_rate==null?null:latest&&latest.interest_rate+'%'],['Tenure',latest&&latest.tenure_months?latest.tenure_months+' months':null],['Monthly EMI',latest&&latest.monthly_emi==null?null:latest&&money(latest.monthly_emi)],['Outstanding',latest&&latest.outstanding_amount==null?null:latest&&money(latest.outstanding_amount)],['Status',latest&&latest.status],['Current Stage',latest&&latest.current_stage]]);
 detail('opsDetails',[['Customer Created',c.created_at?new Date(c.created_at).toLocaleString('en-IN'):null],['Documents',docs.length],['Loans',loans.length],['Repayment Records',reps.length],['Profile Source','DirectCredit customer record'],['Decision Source',risk.source||'Not assessed'],['Audit Trail','Available through admin audit controls'],['Communication','Customer contact history'],['Data Mode','Admin portal detail view']]);document.getElementById('latestLoan').innerHTML=latest?[['Loan Account',latest.id],['Product',latest.product],['Requested',money(latest.requested_amount)],['Eligible',money(latest.eligible_amount)],['Sanctioned',money(latest.sanctioned_amount)],['Disbursed',money(latest.disbursed_amount)],['EMI',money(latest.monthly_emi)],['Outstanding',money(latest.outstanding_amount)],['Tenure',latest.tenure_months?`${latest.tenure_months} months`:null],['Scorecard',latest.scorecard_score==null?'Not assessed':`${latest.scorecard_score}/${latest.scorecard_max||125}`],['Status',latest.status],['Current Stage',latest.current_stage]].map(([k,v])=>`<label>${esc(k)} <b>${esc(text(v))}</b></label>`).join(''):'<div class="empty-state">No live loan record exists for this customer.</div>';
 document.getElementById('loanRows').innerHTML=loans.length?loans.map(l=>`<tr><td>${esc(text(l.id))}</td><td>${esc(text(l.product))}</td><td>${esc(money(l.requested_amount))}</td><td>${esc(money(l.sanctioned_amount))}</td><td>${esc(money(l.disbursed_amount))}</td><td>${esc(money(l.outstanding_amount))}</td><td>${esc(money(l.monthly_emi))}</td><td>${esc(text(l.next_due_date||l.due_date))}</td><td>${esc(text(l.status))}</td></tr>`).join(''):'<tr><td colspan="9">No live loan records.</td></tr>';
 document.getElementById('repaymentRows').innerHTML=reps.length?reps.slice(0,10).map(r=>`<tr><td>${esc(text(r.due_date))}</td><td>${esc(text(r.loan_id))}</td><td>${esc(money(r.paid_amount||r.due_amount))}</td><td>${esc(text(r.status))}</td></tr>`).join(''):'<tr><td colspan="4">No live repayment records.</td></tr>';
 document.getElementById('documentRows').innerHTML=docs.length?docs.map(d=>`<tr><td>${esc(text(d.document_type))}</td><td>${esc(text(d.verification_status))}</td><td>${esc(d.created_at?new Date(d.created_at).toLocaleDateString('en-IN'):'Not available')}</td></tr>`).join(''):'<tr><td colspan="3">No live document records.</td></tr>';
}
async function load(){const id=idFromUrl();if(!id){document.querySelector('.right-area').innerHTML='<div class="panel empty-state"><h2>No customer selected</h2><p>Open this page with a valid customer_id from a live customer record.</p></div>';return;}try{const r=await fetch(`${API_BASE}/admin/reports/customer/${id}/profile`,{headers:adminHeaders()});if(!r.ok)throw new Error(String(r.status));render(await r.json());}catch(e){document.querySelector('.right-area').innerHTML='<div class="panel empty-state"><h2>Live customer data unavailable</h2><p>Use an authorized admin session. No demo or fallback customer data is displayed.</p></div>';}}
load();
