const customerSteps=[
 {key:'pan',label:'PAN',title:'PAN Number',text:'Enter your PAN number. Demo mode checks the PAN format and records a temporary verification result.',body:`<label>PAN Number<input id="cPan" placeholder="ABCDE1234F" maxlength="10"></label><div class="info-box" id="cPanResult">PAN name verification: <b>Pending</b></div>`},
 {key:'aadhaar',label:'Aadhaar OCR / Verification',title:'Aadhaar OCR / Verification',text:'Upload your Aadhaar card for OCR and verification. Production verification can be connected later.',body:`<label>Aadhaar Card<input id="cAadhaar" type="file" accept="image/*,.pdf"></label><div class="info-box" id="cAadhaarResult">OCR status: <b>Waiting for upload</b></div>`},
 {key:'selfie',label:'Selfie',title:'Selfie Verification',text:'Capture or upload a selfie for identity and liveness verification.',body:`<label>Selfie<input id="cSelfie" type="file" accept="image/*" capture="user"></label><div class="info-box" id="cSelfieResult">Face/liveness status: <b>Pending</b></div>`},
 {key:'bureau',label:'Bureau',title:'Credit Bureau Check',text:'Your credit bureau information is checked as part of the loan assessment.',body:`<div class="score-box"><div><small>Credit Score</small><strong>782</strong></div><div><small>DPD</small><strong>0</strong></div><div><small>Active Loans</small><strong>1</strong></div><div><small>Enquiries</small><strong>2</strong></div></div>`},
 {key:'profile',label:'Profile',title:'Profile Details',text:'Review and confirm your personal and business details.',body:`<div class="detail-list"><div><span>Name</span><b>Rajesh Kumar</b></div><div><span>Mobile</span><b>+91 98765 43210</b></div><div><span>Address</span><b>Ahmedabad, Gujarat</b></div><div><span>Business</span><b>Kumar Traders</b></div><div><span>Business Type</span><b>Wholesale Trading</b></div></div>`},
 {key:'bank',label:'Bank Statement & Analysis',title:'Bank Statement Upload & Our Analysis',text:'Upload your bank statement. DirectCredit analyses the statement using its own analysis engine.',body:`<label>Bank Statement<input id="cBank" type="file" accept=".pdf,.csv,.xls,.xlsx"></label><div class="info-box" id="cBankResult">Analysis status: <b>Waiting for statement</b></div>`},
 {key:'documents',label:'Other Documents',title:'Other Documents',text:'Upload supporting business or income documents when required.',body:`<div class="detail-list"><div><span>PAN Card</span><b class="green-text">Verified</b></div><div><span>Aadhaar Card</span><b class="green-text">Verified</b></div><div><span>Bank Statement</span><b class="green-text">Verified</b></div><div><span>Business Proof</span><b>Required if applicable</b></div></div><label>Additional Document<input id="cDoc" type="file" accept=".pdf,image/*"></label>`},
 {key:'assessment',label:'Loan Assessment',title:'Loan Assessment',text:'Your eligibility is calculated from identity, bureau, profile, bank analysis and supporting documents.',body:`<div class="score-box"><div><small>Eligibility Score</small><strong>92.65 / 110</strong></div><div><small>Risk Category</small><strong class="green-text">Low Risk</strong></div><div><small>Recommended Limit</small><strong>₹15,000</strong></div><div><small>Decision</small><strong class="green-text">Eligible</strong></div></div>`},
 {key:'sanction',label:'Sanction',title:'Sanction',text:'Your approved loan offer is shown below for review.',body:`<div class="approval-box"><span class="approved">APPROVED</span><h2>₹15,000</h2><p>Micro Business Loan · Monthly repayment</p><p>Recommended tenure: <b>12 Months</b></p></div>`},
 {key:'customerApproval',label:'Customer Approval',title:'Customer Approval',text:'Review the sanctioned amount and give your consent to continue.',body:`<div class="approval-box"><h2>₹15,000</h2><p>Approved loan amount</p><label><input id="cConsent" type="checkbox" style="width:auto;display:inline-block;margin-right:8px"> I approve the loan offer and sanction details.</label></div>`},
 {key:'esign',label:'E-Sign',title:'E-Sign Agreement',text:'Review the loan agreement and complete the e-sign step. Demo mode records a temporary success.',body:`<div class="info-box">Agreement status: <b>Ready for E-Sign</b></div>`},
 {key:'disbursement',label:'Disbursement',title:'Disbursement',text:'After approval and e-sign, the loan moves to disbursement. Demo mode records a temporary success.',body:`<div class="info-box">Disbursement status: <b>Ready for Disbursement</b></div>`},
 {key:'repayment',label:'Repayment',title:'Repayment Schedule',text:'Your loan is active and the monthly repayment schedule is available here.',body:`<div class="score-box"><div><small>Loan Amount</small><strong>₹15,000</strong></div><div><small>Monthly Repayment</small><strong>₹1,375</strong></div><div><small>Status</small><strong class="green-text">Active</strong></div><div><small>Frequency</small><strong>Monthly</strong></div></div>`}
];
let cCurrent=Number(localStorage.getItem('dcCustomerStep')||0);let cDone=JSON.parse(localStorage.getItem('dcCustomerDone')||'[]');
function saveCustomer(){localStorage.setItem('dcCustomerStep',String(cCurrent));localStorage.setItem('dcCustomerDone',JSON.stringify(cDone));}
function renderJourney(){const rail=document.getElementById('journeyRail');if(!rail)return;rail.innerHTML=customerSteps.map((s,i)=>`<button class="journey-step ${i===cCurrent?'current':''} ${cDone.includes(s.key)?'done':''}" onclick="goCustomerStep(${i})"><span class="num">${cDone.includes(s.key)?'✓':i+1}</span><span>${s.label}</span></button>`).join('');}
function renderHomeJourney(){const host=document.getElementById('homeJourney');if(!host)return;host.innerHTML=`<div class="home-journey-head"><div><span class="eyebrow">LOAN APPLICATION JOURNEY</span><h2>Complete Your Loan Application</h2><p>13 steps from verification to repayment. Your progress is saved automatically.</p></div><span class="demo-badge">${cDone.length} / ${customerSteps.length} Completed</span></div><div class="home-journey-body"><div class="home-step-list">${customerSteps.map((s,i)=>`<button class="home-step ${i===cCurrent?'current':''} ${cDone.includes(s.key)?'done':''}" onclick="goHomeStep(${i})"><span class="home-step-num">${cDone.includes(s.key)?'✓':i+1}</span><span class="home-step-label"><b>${s.label}</b><small>${s.title}</small></span><span class="home-step-status">${cDone.includes(s.key)?'Completed':i===cCurrent?'Current':'Pending'}</span></button>`).join('')}</div><div class="home-step-summary"><span class="eyebrow">CURRENT STEP</span><h3>Step ${cCurrent+1} of ${customerSteps.length}</h3><h2>${customerSteps[cCurrent].title}</h2><p>${customerSteps[cCurrent].text}</p><button class="primary" onclick="openCustomerCurrentStep()">Continue Current Step →</button></div></div>`;}
function goHomeStep(i){if(i<=cCurrent||cDone.includes(customerSteps[i-1]?.key)){cCurrent=i;saveCustomer();renderHomeJourney();openSection('application');}}
function openCustomerCurrentStep(){openSection('application');}
function renderStep(){const s=customerSteps[cCurrent];document.getElementById('stepPanel').innerHTML=`<div class="step-body"><span class="eyebrow">STEP ${cCurrent+1} OF ${customerSteps.length}</span><h2>${s.title}</h2><p>${s.text}</p>${s.body}<div class="step-actions">${cCurrent>0?'<button class="outline" onclick="goCustomerStep('+ (cCurrent-1) +')">← Back</button>':''}<button class="primary" id="customerNext">${cCurrent===customerSteps.length-1?'Finish':'Complete & Continue →'}</button></div><div id="customerSuccess"></div></div>`;bindStep();}
function bindStep(){const s=customerSteps[cCurrent];const next=document.getElementById('customerNext');next.onclick=completeCustomerStep;if(s.key==='pan'){document.getElementById('cPan').oninput=e=>e.target.value=e.target.value.toUpperCase();}if(s.key==='aadhaar')document.getElementById('cAadhaar').onchange=e=>{if(e.target.files[0])document.getElementById('cAadhaarResult').innerHTML='<b>Document received.</b> Demo OCR fields captured successfully.'};if(s.key==='selfie')document.getElementById('cSelfie').onchange=e=>{if(e.target.files[0])document.getElementById('cSelfieResult').innerHTML='<b>Selfie received.</b> Demo face/liveness verification ready.'};if(s.key==='bank')document.getElementById('cBank').onchange=e=>{if(e.target.files[0])document.getElementById('cBankResult').innerHTML='<b>Statement received.</b> Our analysis engine is ready to analyse the file.'};}
function completeCustomerStep(){const s=customerSteps[cCurrent];if(s.key==='pan'){const v=document.getElementById('cPan').value.trim();if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(v)){alert('Enter a valid PAN format, for example ABCDE1234F.');return;}document.getElementById('cPanResult').innerHTML='<b>Demo Verified</b> · PAN format and name match successful.';}if(s.key==='aadhaar'&&!document.getElementById('cAadhaar').files[0]){alert('Please upload Aadhaar card.');return;}if(s.key==='selfie'&&!document.getElementById('cSelfie').files[0]){alert('Please capture or upload your selfie.');return;}if(s.key==='bank'&&!document.getElementById('cBank').files[0]){alert('Please upload a bank statement.');return;}if(s.key==='customerApproval'&&!document.getElementById('cConsent').checked){alert('Please approve the loan offer before continuing.');return;}if(!cDone.includes(s.key))cDone.push(s.key);saveCustomer();const box=document.getElementById('customerSuccess');box.innerHTML='<div class="success">✓ '+s.label+' completed successfully.</div>';if(cCurrent<customerSteps.length-1){setTimeout(()=>{cCurrent++;saveCustomer();renderJourney();renderStep();renderHomeJourney();},350);}else{setTimeout(()=>{renderHomeJourney();alert('Customer loan journey completed successfully.');},350);}}
function goCustomerStep(i){if(i<=cCurrent||cDone.includes(customerSteps[i-1]?.key)){cCurrent=i;saveCustomer();renderJourney();renderStep();renderHomeJourney();}}
function openSection(id){document.querySelectorAll('.customer-section').forEach(x=>x.classList.remove('active-section'));document.getElementById(id).classList.add('active-section');document.querySelectorAll('.side-nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));document.getElementById('pageTitle').textContent=document.querySelector(`[data-section="${id}"]`)?.textContent.trim()||'Dashboard';if(id==='application'){renderJourney();renderStep();}}
function initPortal(){document.getElementById('loginView').classList.add('hidden');document.getElementById('portalView').classList.remove('hidden');renderJourney();renderStep();renderHomeJourney();document.getElementById('homeProgress').innerHTML=`<div class="progress-summary"><b>Step ${cCurrent+1} of ${customerSteps.length}</b><div class="progress-bar"><div class="progress-fill" style="width:${Math.round(((cCurrent+(cDone.includes(customerSteps[cCurrent]?.key)?1:0))/customerSteps.length)*100)}%"></div></div><b>${Math.round((cDone.length/customerSteps.length)*100)}%</b></div>`;}
document.getElementById('loginBtn').onclick=()=>{if(!document.getElementById('loginId').value.trim()||!document.getElementById('loginPassword').value.trim()){alert('Enter Customer ID and password/OTP.');return;}sessionStorage.setItem('dcCustomerLoggedIn','1');initPortal();};document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem('dcCustomerLoggedIn');location.reload();};document.querySelectorAll('.side-nav').forEach(b=>b.onclick=()=>openSection(b.dataset.section));if(sessionStorage.getItem('dcCustomerLoggedIn')==='1')initPortal();