(function(){
  const dash=document.getElementById('dashboard'); if(!dash)return;
  const fmt=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
  window.__dcRenderDashboard=function(d){
    const kpis=[['Total Users','Customers in database',d.customers.total,'blue','♙'],['Active Loans','Currently active loans',d.active_loans,'purple','▣'],['Overdue Loans','Loans currently overdue',d.overdue_loans,'red','⚠'],['Outstanding Amount','Active + overdue outstanding',fmt(d.amounts.outstanding),'green','$'],['Paid Amount','Repayment cash received',fmt(d.amounts.paid),'orange','↘'],['Total Disbursed','Lifetime disbursed amount',fmt(d.amounts.disbursed),'teal','↗'],['Total Due','Repayment amount due',fmt(d.amounts.due),'amber','↘'],['Pending Applications','Applications awaiting decision',d.pending,'pink','▤']];
    const m=d.monthly||[];const max=Math.max(1,...m.map(x=>x.applications));const pts=m.map((x,i)=>`${18+i*540/Math.max(1,m.length-1)},${180-(x.applications/max)*150}`).join(' ');
    dash.innerHTML=`<div class="dc-head"><div><b>Dashboard:</b><span>Live loan pipeline and portfolio data</span></div><button class="dc-refresh" onclick="location.reload()">⟳ &nbsp;Refresh</button></div><div class="dc-title">Dashboard</div><div class="dc-kpis">${kpis.map(k=>`<div class="dc-kpi ${k[3]}"><div class="dc-kpi-icon">${k[4]}</div><div class="dc-kpi-info"><div class="dc-kpi-name">${k[0]} <span>ⓘ</span></div><div class="dc-kpi-sub">${k[1]}</div><strong>${k[2]}</strong></div></div>`).join('')}</div><div class="dc-main-grid"><div class="dc-left"><div class="dc-panel dc-trend"><div class="dc-panel-head"><h3>Application Trend</h3><span>Live database</span></div><div class="dc-chart"><svg viewBox="0 0 570 205" preserveAspectRatio="none"><polyline points="${pts}" fill="none" class="trend-line"/>${m.map((x,i)=>`<circle class="trend-dot" cx="${18+i*540/Math.max(1,m.length-1)}" cy="${180-(x.applications/max)*150}" r="3"/>`).join('')}</svg><div class="dc-xlabels">${m.map(x=>`<span>${x.month}</span>`).join('')}</div></div></div><div class="dc-panel dc-recent"><div class="dc-panel-head"><h3>Recent Loans</h3></div><table><thead><tr><th>Loan ID</th><th>Customer ID</th><th>Loan Amount</th><th>Status</th><th>Created</th></tr></thead><tbody>${d.recent_loans.length?d.recent_loans.map(l=>`<tr><td>LN${String(l.id).padStart(8,'0')}</td><td>${l.customer_id}</td><td>${fmt(l.amount)}</td><td><span class="dc-status">${l.status}</span></td><td>${l.created_at?new Date(l.created_at).toLocaleDateString('en-IN'):'—'}</td></tr>`).join(''):'<tr><td colspan="5">No live loans available.</td></tr>'}</tbody></table></div></div><div class="dc-right"><div class="dc-panel dc-summary"><div class="dc-panel-head"><h3>Summary</h3></div><div class="dc-row"><span>Applications</span><b>${d.applications}</b></div><div class="dc-row"><span>Pending</span><b>${d.pending}</b></div><div class="dc-row"><span>Disbursed</span><b>${d.disbursed_count}</b></div><div class="dc-row danger"><span>Overdue</span><b>${d.overdue_loans}</b></div><div class="dc-row success"><span>Repaid</span><b>${d.repaid_loans}</b></div></div><div class="dc-panel dc-notify"><div class="dc-panel-head"><h3>Data status</h3></div><div class="dc-notice"><div class="dc-avatar">✓</div><div><b>Live database connected</b><small>Figures on this dashboard are calculated from current records.</small></div></div></div></div></div>`;
  };
  const base=(localStorage.getItem('directcredit_api_url')||window.DIRECTCREDIT_API_URL||'/api').replace(/\/$/,'');
  fetch(base+'/admin/reporting').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(window.__dcRenderDashboard).catch(()=>{dash.innerHTML='<div class="dc-panel"><h3>Live dashboard unavailable</h3><p>Connect the DirectCredit API. No demo totals are displayed.</p></div>';});
})();
