(function(){
const el=document.getElementById('reports');if(!el)return;
const tabs=[['Registration & Users','Registered users, MoM matrix, and onboarding...','users'],['Loan Pipeline','Approval → E-Sign → E-Mandate → Disbursement','pipeline'],['Disbursement Matrix','Disbursement counts by date/time → new vs repeat','disbursement'],['Loan Slab Performance','Active, overdue & repaid by loan amount slab','slab'],['Repayment Matrix','Due-date collection matrix — cash received → DPD','repayment'],['Due Calendar','Month-wise due-date collection calendar and status','calendar']];
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const pct=(a,b)=>b?((a/b)*100).toFixed(1)+'%':'0.0%';
function table(title,head,rows){return `<div class="fr-panel fr-wide"><h3>${title}</h3><div class="fr-table-scroll"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}">No live data available.</td></tr>`}</tbody></table></div></div>`}
function shell(d){el.innerHTML=`<div class="fr-head"><div><h2>Funnel & Matrix Reports</h2><p>Live reporting from DirectCredit database</p><small>Updated ${new Date(d.generated_at).toLocaleString('en-IN')}</small></div><div class="fr-admin"><div class="fr-admin-avatar">●</div><div><b>Service Matrimony</b><span>Super Admin</span></div><button type="button" class="fr-refresh">⟳ &nbsp;Refresh</button></div></div><div class="fr-tabs">${tabs.map((t,i)=>`<button type="button" class="fr-tab ${i===0?'selected':''}" data-report-tab="${t[2]}"><span class="fr-tab-icon">${['♙','▤','$','▦','%','□'][i]}</span><div><b>${t[0]}</b><small>${t[1]}</small></div></button>`).join('')}</div><div class="fr-filter"><div class="fr-filter-label">▣ <b>Reporting period</b><small>Live database totals</small></div><button type="button" class="fr-apply" id="reportRefresh">Refresh</button></div><div id="reportView"></div>`;
const view=document.getElementById('reportView');
function users(){const c=d.customers;const rows=[['Customers',c.total,c.active,c.incomplete,pct(c.active,c.total)],['KYC verified',c.kyc_verified,'—','—',pct(c.kyc_verified,c.total)]];return `<h3 class="fr-section-title">Registered Users <span>ⓘ</span></h3><div class="fr-kpis">${[['Total Registered',c.total,'blue'],['Active Customers',c.active,'green'],['KYC Verified',c.kyc_verified,'teal'],['Profile Incomplete',c.incomplete,'purple']].map(k=>`<div class="fr-kpi ${k[2]}"><span class="fr-kpi-icon">●</span><div><b>${k[0]}</b><strong>${k[1]}</strong></div></div>`).join('')}</div><div class="fr-bottom">${table('Customer summary',['METRIC','TOTAL','ACTIVE','INCOMPLETE','ACTIVE %'],rows)}${table('Onboarding stages',['STAGE','COUNT','% OF CUSTOMERS'],[['Applications',d.applications,pct(d.applications,c.total)],['Unique applicants',d.unique_users,pct(d.unique_users,c.total)],['Pending',d.pending,pct(d.pending,d.applications)],['Rejected / Dropped',d.rejected,pct(d.rejected,d.applications)],['Disbursed',d.disbursed_count,pct(d.disbursed_count,d.applications)]])}</div>`}
function pipeline(){return `<div class="fr-bottom">${table('Loan Pipeline',['STAGE','COUNT','% OF TOTAL','STATUS'],[['Applications',d.applications,'100%','Tracked'],['Unique Users',d.unique_users,pct(d.unique_users,d.applications),'Tracked'],['Repeat Users',d.repeat_users,pct(d.repeat_users,d.unique_users),'Tracked'],['Pending',d.pending,pct(d.pending,d.applications),'Pending'],['Rejected / Dropped',d.rejected,pct(d.rejected,d.applications),'Rejected'],['Disbursement',d.disbursed_count,pct(d.disbursed_count,d.applications),'Disbursed'],['Active',d.active_loans,pct(d.active_loans,d.applications),'Active'],['Overdue',d.overdue_loans,pct(d.overdue_loans,d.applications),'Overdue'],['Repaid',d.repaid_loans,pct(d.repaid_loans,d.applications),'Completed']])}</div>`}
function disbursement(){const m=d.monthly;return table('Disbursement Matrix',['METRIC',...m.map(x=>x.month),'TOTAL'],[['Applications',...m.map(x=>x.applications),d.applications],['Disbursed Count',...m.map(x=>x.disbursed_count),d.disbursed_count],['Disbursed Amount',...m.map(x=>money(x.disbursed_amount)),money(d.amounts.disbursed)]])}
function slab(){return table('Loan Slab Performance',['LOAN AMOUNT','TOTAL','ACTIVE','OVERDUE','REPAID','DISBURSED / OUTSTANDING'],d.slabs.map(x=>[money(x.amount),x.total_count,x.active_count,x.overdue_count,x.repaid_count,money(x.active_amount+x.overdue_amount)]))}
function repayment(){const s=d.repayment_status;const keys=['On-Time / Paid','Overdue DPD 1–30','Overdue DPD 31–60','Overdue DPD 61–90','NPA DPD 90+','Upcoming'];return `<div class="fr-kpis">${[['AMOUNT DUE',money(d.amounts.due),'blue'],['PAID SO FAR',money(d.amounts.paid),'green'],['STILL UNPAID',money(d.amounts.unpaid),'orange'],['OVERDUE',money(d.amounts.overdue),'red']].map(k=>`<div class="fr-kpi ${k[2]}"><div><b>${k[0]}</b><strong>${k[1]}</strong></div></div>`).join('')}</div>${table('Repayment Matrix',['STATUS','COUNT','DUE','PAID','UNPAID','% PAID'],keys.map(k=>{const x=s[k]||{count:0,due:0,paid:0,unpaid:0};return [k,x.count,money(x.due),money(x.paid),money(x.unpaid),pct(x.paid,x.due)]}))}`}
function calendar(){return table('Due Calendar',['DUE DATE','CASE COUNT','AMOUNT DUE','PAID','UNPAID','STATUS'],d.due_calendar.map(x=>[x.date,x.count,money(x.due),money(x.paid),money(x.due-x.paid),x.due>x.paid?'Due / Partially paid':'Paid']))}
const views={users,pipeline,disbursement,slab,repayment,calendar};
function activate(key){document.querySelectorAll('.fr-tab').forEach(b=>b.classList.toggle('selected',b.dataset.reportTab===key));view.innerHTML=views[key]();}
function bind(){document.querySelectorAll('.fr-tab').forEach(b=>b.onclick=()=>{activate(b.dataset.reportTab)});document.getElementById('reportRefresh').onclick=load;document.querySelector('.fr-refresh').onclick=load;activate('users');}
async function load(){view.innerHTML='<div class="fr-panel"><h3>Loading live reporting data…</h3></div>';try{d=await DirectCreditData.reporting();shell(d);bind();}catch(err){view.innerHTML=`<div class="fr-panel"><h3>Live data unavailable</h3><p>Connect the DirectCredit API to show database-backed figures. No demo totals are displayed.</p></div>`;}}
let d={};load();
})();
