from sqlalchemy import Column, DateTime, Float, Integer, String, Text, Boolean
from sqlalchemy.sql import func
from .database import Base

class CustomerRecord(Base):
    __tablename__ = "customers"
    id = Column(Integer, primary_key=True, index=True)
    customer_code = Column(String(80), unique=True, index=True)
    login_id = Column(String(120), unique=True, index=True)
    password_hash = Column(Text)
    name = Column(String(200), nullable=False)
    pan = Column(String(20), unique=True, index=True)
    mobile = Column(String(30), index=True)
    email = Column(String(200))
    address = Column(Text)
    permanent_address = Column(Text)
    current_city = Column(String(100))
    gender = Column(String(40))
    business_name = Column(String(200))
    business_type = Column(String(120))
    date_of_birth = Column(String(20))
    aadhaar_masked = Column(String(30))
    marital_status = Column(String(40))
    customer_type = Column(String(40), default="Individual")
    occupation = Column(String(100), default="Business")
    monthly_income = Column(Float, default=0)
    work_experience_years = Column(Float, default=0)
    years_in_business = Column(Float, default=0)
    average_bank_balance = Column(Float, default=0)
    primary_bank = Column(String(120))
    cibil_score = Column(Integer, default=0)
    foir = Column(Float, default=0)
    existing_emi = Column(Float, default=0)
    dependents = Column(Integer, default=0)
    residence_ownership = Column(String(50))
    residence_since = Column(String(50))
    ownership_proof_name = Column(String(255))
    ownership_proof_status = Column(String(40), default="pending")
    kyc_status = Column(String(40), default="pending")
    email_verified = Column(String(20), default="pending")
    selfie_status = Column(String(40), default="pending")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    session_version = Column(Integer, nullable=False, default=1, server_default="1")

class LoanRecord(Base):
    __tablename__ = "loan_applications"
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, index=True, nullable=False)
    requested_amount = Column(Float, nullable=False)
    eligible_amount = Column(Float, default=0)
    monthly_emi = Column(Float, default=0)
    sanctioned_amount = Column(Float, default=0)
    disbursed_amount = Column(Float, default=0)
    outstanding_amount = Column(Float, default=0)
    interest_rate = Column(Float, default=0)
    tenure_months = Column(Integer, default=6)
    status = Column(String(50), default="draft", index=True)
    current_stage = Column(String(50), default="PAN", index=True)
    product = Column(String(120), default="Micro Business Loan")
    disbursement_details = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class DocumentRecord(Base):
    __tablename__ = "documents"
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, index=True, nullable=False)
    loan_id = Column(Integer, index=True)
    document_type = Column(String(80), nullable=False)
    document_role = Column(String(80), default="supporting")
    file_name = Column(String(255), nullable=False)
    mime_type = Column(String(120))
    file_size = Column(Integer, default=0)
    checksum = Column(String(128), index=True)
    source = Column(String(40), default="customer_portal")
    required = Column(Boolean, default=False)
    verification_status = Column(String(40), default="pending", index=True)
    verified_by = Column(String(120))
    verified_at = Column(DateTime(timezone=True))
    rejection_reason = Column(Text)
    storage_provider = Column(String(50))
    storage_key = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class RepaymentRecord(Base):
    __tablename__ = "repayments"
    id = Column(Integer, primary_key=True, index=True)
    loan_id = Column(Integer, index=True, nullable=False)
    installment = Column(Integer, nullable=False)
    due_date = Column(String(20), nullable=False)
    due_amount = Column(Float, nullable=False)
    paid_amount = Column(Float, default=0)
    status = Column(String(30), default="upcoming", index=True)
    payment_reference = Column(String(160), index=True)
    payment_method = Column(String(40))
    paid_at = Column(DateTime(timezone=True))
    bounce_reason = Column(Text)

class CustomerJourneyRecord(Base):
    __tablename__ = "customer_journey"
    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, index=True, nullable=False)
    loan_id = Column(Integer, index=True)
    step_key = Column(String(80), index=True, nullable=False)
    step_number = Column(Integer, default=0)
    step_label = Column(String(160))
    status = Column(String(40), default="pending")
    details = Column(Text)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class AuditEventRecord(Base):
    __tablename__ = "audit_events"
    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(String(36), unique=True, nullable=False, index=True)
    event_time = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    actor_type = Column(String(40), nullable=False, index=True)
    actor_id = Column(String(120), index=True)
    action = Column(String(100), nullable=False, index=True)
    entity_type = Column(String(80), nullable=False, index=True)
    entity_id = Column(String(120), index=True)
    customer_id = Column(Integer, index=True)
    loan_id = Column(Integer, index=True)
    request_id = Column(String(36), index=True)
    source = Column(String(60), default="api", index=True)
    outcome = Column(String(30), default="success", index=True)
    reason_code = Column(String(100), index=True)
    details = Column(Text)
    ip_address = Column(String(64))
    user_agent = Column(Text)
