"""Phase 1: Customer 360 foundation."""
from alembic import op
import sqlalchemy as sa

revision = "0008_phase1_customer_360"
down_revision = "0007_loan_settlements"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("customer_businesses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("legal_name", sa.String(200), nullable=False), sa.Column("trade_name", sa.String(200)), sa.Column("business_type", sa.String(80)), sa.Column("constitution", sa.String(80)), sa.Column("pan", sa.String(20)), sa.Column("gstin", sa.String(30)), sa.Column("industry", sa.String(120)), sa.Column("sub_industry", sa.String(120)), sa.Column("business_vintage_years", sa.Numeric(8,2)), sa.Column("annual_turnover", sa.Numeric(18,2)), sa.Column("monthly_turnover", sa.Numeric(18,2)), sa.Column("employee_count", sa.Integer()), sa.Column("ownership_type", sa.String(50)), sa.Column("verification_status", sa.String(40), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_businesses_customer_id", "customer_businesses", ["customer_id"])
    op.create_index("ix_customer_businesses_gstin", "customer_businesses", ["gstin"])
    op.create_table("customer_contacts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("contact_type", sa.String(40), nullable=False), sa.Column("contact_value", sa.String(255), nullable=False), sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("verification_status", sa.String(40), nullable=False, server_default="pending"), sa.Column("verified_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_contacts_customer_id", "customer_contacts", ["customer_id"])
    op.create_index("ix_customer_contacts_value", "customer_contacts", ["contact_value"])
    op.create_table("customer_addresses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("address_type", sa.String(40), nullable=False), sa.Column("address_line_1", sa.Text()), sa.Column("address_line_2", sa.Text()), sa.Column("area", sa.String(160)), sa.Column("city", sa.String(100)), sa.Column("district", sa.String(100)), sa.Column("state", sa.String(100)), sa.Column("pin_code", sa.String(12)), sa.Column("country", sa.String(80), server_default="India"), sa.Column("latitude", sa.Numeric(10,7)), sa.Column("longitude", sa.Numeric(10,7)), sa.Column("verification_status", sa.String(40), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_addresses_customer_id", "customer_addresses", ["customer_id"])
    op.create_table("customer_kyc_profiles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False, unique=True), sa.Column("status", sa.String(40), nullable=False, server_default="not_started"), sa.Column("pan_status", sa.String(40), server_default="pending"), sa.Column("identity_status", sa.String(40), server_default="pending"), sa.Column("address_status", sa.String(40), server_default="pending"), sa.Column("business_status", sa.String(40), server_default="pending"), sa.Column("aadhaar_reference", sa.String(120)), sa.Column("last_verified_at", sa.DateTime(timezone=True)), sa.Column("verification_source", sa.String(80)), sa.Column("verification_reference", sa.String(160)), sa.Column("review_reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("customer_bank_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("bank_name", sa.String(160), nullable=False), sa.Column("account_holder_name", sa.String(200)), sa.Column("account_number_masked", sa.String(40), nullable=False), sa.Column("account_number_fingerprint", sa.String(128)), sa.Column("ifsc", sa.String(20)), sa.Column("account_type", sa.String(40)), sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("verification_status", sa.String(40), nullable=False, server_default="pending"), sa.Column("verified_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_bank_accounts_customer_id", "customer_bank_accounts", ["customer_id"])
    op.create_index("ix_customer_bank_accounts_fingerprint", "customer_bank_accounts", ["account_number_fingerprint"])
    op.create_table("customer_consents", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("consent_type", sa.String(80), nullable=False), sa.Column("purpose", sa.Text()), sa.Column("version", sa.String(40), nullable=False), sa.Column("accepted", sa.Boolean(), nullable=False), sa.Column("channel", sa.String(40)), sa.Column("accepted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("withdrawn_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_consents_customer_id", "customer_consents", ["customer_id"])
    op.create_index("ix_customer_consents_type", "customer_consents", ["consent_type"])
    op.create_table("customer_preferences", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False, unique=True), sa.Column("sms", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("email", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("whatsapp", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("phone", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("push", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("transactional_only", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("customer_risk_profiles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False, unique=True), sa.Column("risk_grade", sa.String(20)), sa.Column("risk_status", sa.String(40), nullable=False, server_default="not_assessed"), sa.Column("fraud_status", sa.String(40), nullable=False, server_default="not_assessed"), sa.Column("credit_status", sa.String(40), nullable=False, server_default="not_assessed"), sa.Column("risk_flags", sa.Text()), sa.Column("last_assessed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("customer_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customer_id", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("event_status", sa.String(40), nullable=False, server_default="completed"), sa.Column("source", sa.String(60)), sa.Column("actor_type", sa.String(40)), sa.Column("actor_id", sa.String(120)), sa.Column("details", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_customer_events_customer_id", "customer_events", ["customer_id"])
    op.create_index("ix_customer_events_type", "customer_events", ["event_type"])

def downgrade():
    for table in ["customer_events","customer_risk_profiles","customer_preferences","customer_consents","customer_bank_accounts","customer_kyc_profiles","customer_addresses","customer_contacts","customer_businesses"]:
        op.drop_table(table)
